import streamlit as st
import pandas as pd
from datetime import datetime

st.header("📊 Student Report Cards")

# Load quiz results and students
if not st.file_exists("data/quiz_results.csv"):
    st.info("No quiz results yet. Students need to take quizzes first.")
else:
    results = pd.read_csv("data/quiz_results.csv")
    students = pd.read_csv("data/students.csv")

    if results.empty:
        st.info("No quiz results yet.")
    else:
        # Merge to get student names
        merged = results.merge(students[['id', 'name']], left_on='student_id', right_on='id')
        merged = merged.sort_values('date', ascending=False)

        # Show each report card in an expander
        for _, row in merged.iterrows():
            with st.expander(f"Report Card - {row['name']} (ID: {row['student_id']}) - {row['score']}/{row['total']} ({row['percentage']:.1f}%) - {row['date']}"):
                st.write(f"**Student Name:** {row['name']}")
                st.write(f"**Student ID:** {row['student_id']}")
                st.write(f"**Quiz Date:** {row['date']}")

                percentage = row['percentage']
                grade = "A" if percentage >= 90 else "B" if percentage >= 80 else "C" if percentage >= 70 else "D" if percentage >= 60 else "F"
                st.write(f"**Score:** {row['score']}/{row['total']} ({percentage:.1f}%)")
                st.write(f"**Grade:** {grade}")

                if grade == "A":
                    st.success("Excellent performance! 🌟")
                elif grade == "B":
                    st.success("Great job! Keep it up! 👍")
                elif grade == "C":
                    st.info("Good effort! Can improve! 💪")
                elif grade == "D":
                    st.warning("Needs improvement! 📚")
                else:
                    st.error("Keep practicing! Don't give up! 🔥")

                # Download button for this report
                report_html = f"""
                <h2>Report Card</h2>
                <p><strong>Student Name:</strong> {row['name']}</p>
                <p><strong>Student ID:</strong> {row['student_id']}</p>
                <p><strong>Date:</strong> {row['date']}</p>
                <p><strong>Score:</strong> {row['score']}/{row['total']} ({percentage:.1f}%)</p>
                <p><strong>Grade:</strong> {grade}</p>
                <hr>
                <p>Generated by Classroom Pro</p>
                """
                st.download_button(
                    label="📄 Download This Report Card (PDF)",
                    data=report_html,
                    file_name=f"report_card_{row['student_id']}_{row['date'].replace('-', '')}.html",
                    mime="text/html",
                    key=f"download_{row['student_id']}_{row['date']}"
                )